sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 155.248.193.129
    port: 3306
    database: changqiong
    username: changqiongroot
    password: cHyPNSJNSaFbzwKp
  minio:
    endpoint: https://minioserver.linqigyqq.top/
    accessKey: DYcsXvmCbrecualEegJ1
    secretKey: anC820RgPhN0QabthUV1qbKUBFzDGeKgoAwurqQQ
    bucketName: changqiongwaimai
